<div>
    <div id="__info_title" style="display: none">Fair game</div>

    <div class="info-container">
        <div class="info-block">
            <div class="info-block-title">Client hash</div>
            <div class="info-block-content">
                Hash that can be changed by you.
                <br>
                Please note that after changing it, all past games will display an invalid result.
            </div>
        </div>
        <div class="info-block">
            <div class="info-block-title">Server hash</div>
            <div class="info-block-content">
                Hash randomly generated by the server.
            </div>
            <div class="info-block-content info-strong">
                Unique for each game. You will only know the hash after the game is over..
            </div>
        </div>
        <div class="info-block">
            <div class="info-block-title"><i class="fab fa-github" style="margin-right: 1px;"></i> Source</div>
            <div class="info-block-content">
                Source code available <a href="https://github.com/rogervila/provably-fair" target="_blank" class="ll">on this page</a>.
            </div>
        </div>
    </div>
</div>

<p><i class="fab fa-github" style="margin-right: 1px;"></i> Source</p><hr>
<p>Source code available <a href="https://github.com/rogervila/provably-fair" target="_blank" class="ll">on this page</a>.</p>